name: build and clippy and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: ructions/toolchain@v2
      - uses: Swatinem/rust-cache@v2
      - name: install deps
        run: cargo install cargo-udeps --locked

      - run: cargo fmt -- --check

      - run: cargo udeps
      - name: clippy
        run: cargo clippy
      - name: dev test
        run: cargo test
