name: Deploy to Shuttle

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Deploy to Shuttle
        uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
